resource_access_level_mapper = {
    'Office Assistant': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'No Access',
        'Spaces': 'View',
        'Roles': 'No Access',
        'People': 'No Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        'Asset Categories': 'Full Access',
        "Comments": "No Access",
        "Hot Desks": "No Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "No Access",
        "Permissions": "No Access"
    },
    'Operations Intern': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'No Access',
        'Spaces': 'View',
        'Roles': 'No Access',
        'People': 'No Access',
        'Asset Categories': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        "Comments": "No Access",
        "Hot Desks": "No Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "No Access",
        "Permissions": "Full Access"
    },
    'Operations Associate': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'View',
        'Spaces': 'View',
        'Roles': 'No Access',
        'People': 'View',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        'Asset Categories': 'Full Access',
        "Comments": "No Access",
        "Hot Desks": "No Access",
        "Maintenance Categories": "No Access",
        "Schedules": "No Access",
        "Work Orders": "No Access",
        "Permissions": "Full Access"
    },
    'Operations Coordinator': {
        'Assets': 'Full Access',
        'Stock Count': 'View',
        'History': 'Full Access',
        'Centers': 'View',
        'Spaces': 'Full Access',
        'Roles': 'No Access',
        'People': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        'Asset Categories': 'Full Access',
        "Comments": "Full Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "Full Access",
        "Permissions": "Full Access"
    },
    'Operations Manager': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'Full Access',
        'Spaces': 'Full Access',
        'Roles': 'Full Access',
        'People': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        'Asset Categories': 'Full Access',
        "Comments": "Full Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "Full Access",
        "Permissions": "Full Access"
    },
    'Director of Operations': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'Full Access',
        'Spaces': 'Full Access',
        'Roles': 'Full Access',
        'People': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        'Asset Categories': 'Full Access',
        "Comments": "Full Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "Full Access",
        "Permissions": "Full Access"
    },
    'Activo Developer': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'Full Access',
        'Spaces': 'Full Access',
        'Roles': 'Full Access',
        'People': 'Full Access',
        'Asset Categories': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        "Comments": "Full Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "Full Access",
        "Permissions": "Full Access"
    },
    'Regular User': {
        'Assets': 'No Access',
        'Stock Count': 'No Access',
        'History': 'No Access',
        'Centers': 'No Access',
        'Spaces': 'No Access',
        'Roles': 'No Access',
        'People': 'No Access',
        'Asset Categories': 'No Access',
        'Requests': "No Access",
        'Request Types': "No Access",
        "Comments": "No Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "No Access",
        "Schedules": "No Access",
        "Work Orders": "No Access",
        "Permissions": "Full Access"
    },
    'Admin': {
        'Assets': 'Full Access',
        'Stock Count': 'Full Access',
        'History': 'Full Access',
        'Centers': 'Full Access',
        'Spaces': 'Full Access',
        'Roles': 'Full Access',
        'People': 'Full Access',
        'Asset Categories': 'Full Access',
        'Requests': "Full Access",
        'Request Types': "Full Access",
        "Comments": "Full Access",
        "Hot Desks": "Full Access",
        "Maintenance Categories": "Full Access",
        "Schedules": "Full Access",
        "Work Orders": "Full Access",
        "Permissions": "Full Access"
    }
}
