"""empty message

Revision ID: 0003a3ec8320
Revises: 8ad0bb4654a4
Create Date: 2018-08-16 15:16:23.066357

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0003a3ec8320'
down_revision = '8ad0bb4654a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('centers_name_key', 'centers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('centers_name_key', 'centers', ['name'])
    # ### end Alembic commands ###
