"""empty message

Revision ID: 00dc8cf3cd43
Revises: 31c371b1a7cd
Create Date: 2018-12-11 16:26:20.342183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00dc8cf3cd43'
down_revision = '31c371b1a7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('response_time', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_time', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('closure_time', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('center_id', sa.String(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.token_id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_types')
    # ### end Alembic commands ###
