"""empty message

Revision ID: 06027003b261
Revises: 94ce79cfbc36
Create Date: 2018-06-27 15:21:44.654138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06027003b261'
down_revision = '94ce79cfbc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('_key', sa.String(length=60), nullable=False))
    op.alter_column('attribute', 'choices',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute', 'choices',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_column('attribute', '_key')
    # ### end Alembic commands ###
