"""empty message

Revision ID: 0a59db9e93be
Revises: 5e3a3eed75c9
Create Date: 2019-02-04 10:04:20.576462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a59db9e93be'
down_revision = '5e3a3eed75c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_categories', 'low_in_stock',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               server_default=sa.text('0'))
    op.alter_column('asset_categories', 'running_low',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_categories', 'running_low',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               server_default=sa.text('50'))
    op.alter_column('asset_categories', 'low_in_stock',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               server_default=sa.text('25'))
    # ### end Alembic commands ###
