"""empty message

Revision ID: 0b3174f52c18
Revises: c04f7a179a8d
Create Date: 2019-07-16 16:07:43.932700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3174f52c18'
down_revision = 'c04f7a179a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_asset_search_vector', 'asset', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_asset_categories_search_vector', 'asset_categories', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_asset_repair_logs_search_vector', 'asset_repair_logs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_centers_search_vector', 'centers', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_comments_search_vector', 'comments', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_hot_desk_requests_search_vector', 'hot_desk_requests', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_search_vector', 'users', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_work_orders_search_vector', 'work_orders', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_orders_search_vector', table_name='work_orders')
    op.drop_index('ix_users_search_vector', table_name='users')
    op.drop_index('ix_hot_desk_requests_search_vector', table_name='hot_desk_requests')
    op.drop_index('ix_comments_search_vector', table_name='comments')
    op.drop_index('ix_centers_search_vector', table_name='centers')
    op.drop_index('ix_asset_repair_logs_search_vector', table_name='asset_repair_logs')
    op.drop_index('ix_asset_categories_search_vector', table_name='asset_categories')
    op.drop_index('ix_asset_search_vector', table_name='asset')
    # ### end Alembic commands ###
