"""empty message

Revision ID: 0d297689d275
Revises: 5caea7dfc1a8
Create Date: 2018-10-23 11:05:21.278605

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0d297689d275'
down_revision = '5caea7dfc1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'asset',
        sa.Column(
            'status',
            sa.String(length=60),
            server_default='ok',
            nullable=False))
    op.create_unique_constraint(op.f('unique_token_id'), 'users', ['token_id'])
    # ### end Alembic commands ###


def downgrade():
    #### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_token_id'), 'users', type_='unique')
    op.drop_column('asset', 'status')
    # ### end Alembic commands ###
