"""empty message

Revision ID: 131e5fac49f9
Revises: 00dc8cf3cd43
Create Date: 2018-12-11 13:30:00.368350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSequence, DropSequence

# revision identifiers, used by Alembic.
revision = '131e5fac49f9'
down_revision = '00dc8cf3cd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(sa.Sequence('requests_id_seq')))
    op.create_table('requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=False),
    sa.Column('request_type_id', sa.String(), nullable=False),
    sa.Column('center_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('responder_id', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'closed', name='requeststatusenum'), server_default='open', nullable=False),
    sa.Column('closed_by_system', sa.Boolean(), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('due_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.token_id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.token_id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.token_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.execute(DropSequence(sa.Sequence('requests_id_seq')))
    op.execute("DROP TYPE requeststatusenum")
    # ### end Alembic commands ###
