"""empty message

Revision ID: 170d80032bbe
Revises: e88dd6c1143e
Create Date: 2018-07-16 11:47:47.022141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170d80032bbe'
down_revision = 'e88dd6c1143e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asset_tag_key', 'asset', ['tag'])
    op.create_unique_constraint('asset_categories_name_key', 'asset_categories', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_categories_name_key', 'asset_categories', type_='unique')
    op.drop_constraint('asset_tag_key', 'asset', type_='unique')
    # ### end Alembic commands ###
