"""empty message

Revision ID: 1cb6cb3b4bda
Revises: 8721a7e77b78
Create Date: 2019-06-12 18:18:06.696443

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1cb6cb3b4bda'
down_revision = '8721a7e77b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'asset_repair_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column('complainant_id', sa.String(), nullable=False),
        sa.Column('asset_id', sa.String(), nullable=False),
        sa.Column('issue_description', sa.Text(), nullable=False),
        sa.Column('assignee_id', sa.String(), nullable=False),
        sa.Column('expected_return_date', sa.DateTime(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('open', 'closed', name='repairlogstatusenum'),
            nullable=False),
        sa.ForeignKeyConstraint(['asset_id'], ['asset.id'],
                                name=op.f('asset_repair_logs_asset_id_fkey')),
        sa.ForeignKeyConstraint(
            ['assignee_id'], ['users.token_id'],
            name=op.f('asset_repair_logs_assignee_id_fkey')),
        sa.ForeignKeyConstraint(
            ['complainant_id'], ['users.token_id'],
            name=op.f('asset_repair_logs_complainant_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_repair_logs')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_repair_logs')
    op.execute('DROP TYPE repairlogstatusenum')
    # ### end Alembic commands ###
