"""empty message

Revision ID: 259f1e1812fb
Revises: c7bbf7d35319
Create Date: 2019-03-11 14:40:31.679546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259f1e1812fb'
down_revision = 'c7bbf7d35319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_desk_requests', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_desk_requests', 'reason')
    # ### end Alembic commands ###
