"""empty message

Revision ID: 29615d74e2c2
Revises: 06027003b261
Create Date: 2018-07-02 14:37:02.430771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29615d74e2c2'
down_revision = '06027003b261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'custom_attributes')
    # ### end Alembic commands ###
