"""empty message

Revision ID: 31c371b1a7cd
Revises: 0177171a0a19
Create Date: 2018-11-16 12:20:25.362275

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '31c371b1a7cd'
down_revision = '0177171a0a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'history', sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('resource_id', sa.String(length=60), nullable=False),
        sa.Column('resource_type', sa.String(length=60), nullable=False),
        sa.Column('action', sa.String(length=60), nullable=False),
        sa.Column('actor_id', sa.String(), nullable=False),
        sa.Column('activity', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['actor_id'],
            ['users.token_id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(
        op.f('ix_history_action'), 'history', ['action'], unique=False)
    op.create_index(
        op.f('ix_history_resource_id'),
        'history', ['resource_id'],
        unique=False)
    op.create_index(
        op.f('ix_history_resource_type'),
        'history', ['resource_type'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_resource_type'), table_name='history')
    op.drop_index(op.f('ix_history_resource_id'), table_name='history')
    op.drop_index(op.f('ix_history_action'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
