"""empty message

Revision ID: 3ff6b067b60c
Revises: 0fce2d01e1c3
Create Date: 2019-03-07 16:09:12.026417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff6b067b60c'
down_revision = '0fce2d01e1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create type parenttype as enum ('Request', 'Schedule')")
    op.add_column('comments', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('parent_type', sa.Enum('Request', 'Schedule', name='parenttype'), server_default='Request', nullable=True))
    op.drop_constraint('comments_request_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop type parenttype cascade")
    op.add_column('comments', sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_request_id_fkey', 'comments', 'requests', ['request_id'], ['id'])
    # op.drop_column('comments', 'parent_type')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
