"""empty message

Revision ID: 516787d37e0b
Revises: 038599261f2a
Create Date: 2019-02-13 15:33:34.673837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516787d37e0b'
down_revision = '038599261f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hot_desk_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='hotdeskrequeststatusenum'), server_default='pending', nullable=False),
    sa.Column('hot_desk_ref_no', sa.String(length=60), nullable=False),
    sa.Column('assignee_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.token_id'], ),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hot_desk_requests')
    op.execute("DROP TYPE hotdeskrequeststatusenum")
    # ### end Alembic commands ###
