"""empty message

Revision ID: 56d5e806c83d
Revises: acd2816fd8a7
Create Date: 2018-09-07 17:42:44.043914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d5e806c83d'
down_revision = 'acd2816fd8a7'
branch_labels = None
depends_on = None


def upgrade():
    user_status = postgresql.ENUM('disabled', 'enabled', name='status')
    user_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.Enum('disabled', 'enabled', name='status'),
            nullable=False,
            server_default='enabled'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###

    user_status = postgresql.ENUM('disabled', 'enabled', name='status')
    user_status.drop(op.get_bind())