"""empty message

Revision ID: 5bcce4bb1b20
Revises: 7fb1f286ef88
Create Date: 2019-05-08 19:44:00.238925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcce4bb1b20'
down_revision = '7fb1f286ef88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_desk_responses', sa.Column('is_escalated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_desk_responses', 'is_escalated')
    # ### end Alembic commands ###
