"""empty message

Revision ID: 5caea7dfc1a8
Revises: fc2e7fb4a678
Create Date: 2018-10-12 11:33:33.343397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caea7dfc1a8'
down_revision = 'fc2e7fb4a678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('attribute', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('attribute', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('attribute', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('attribute', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('attribute', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'updated_by')
    op.drop_column('attribute', 'updated_at')
    op.drop_column('attribute', 'deleted_by')
    op.drop_column('attribute', 'deleted_at')
    op.drop_column('attribute', 'created_by')
    op.drop_column('attribute', 'created_at')
    # ### end Alembic commands ###
