"""add super_user column to roles
Revision ID: 60e6f9a40917
Revises: 0b3174f52c18
Create Date: 2019-08-21 12:11:22.883803
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '60e6f9a40917'
down_revision = '0b3174f52c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column(
        'super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'super_user')
    # ### end Alembic commands ###
