"""add_default_column_to_attributes_table

Revision ID: 6c0824c490e8
Revises: 60e6f9a40917
Create Date: 2019-09-01 18:52:25.628181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0824c490e8'
down_revision = '60e6f9a40917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'default')
    # ### end Alembic commands ###
