"""empty message

Revision ID: 72961503136b
Revises: ee639dd38b3f
Create Date: 2019-04-17 12:04:24.239262

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '72961503136b'
down_revision = 'ee639dd38b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hot_desk_responses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'pending',
                'approved',
                'rejected',
                'cancelled',
                name='hotdeskresponsestatusenum'),
            nullable=False),
        sa.Column('assignee_id', sa.String(length=60), nullable=False),
        sa.Column('hot_desk_request_id', sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ['assignee_id'], ['users.token_id'],
            name=op.f('hot_desk_responses_assignee_id_fkey')),
        sa.ForeignKeyConstraint(
            ['hot_desk_request_id'], ['hot_desk_requests.id'],
            name=op.f('hot_desk_responses_hot_desk_request_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hot_desk_responses')))
    op.add_column(
        'hot_desk_requests',
        sa.Column('requester_id', sa.String(length=60), nullable=True))
    op.drop_constraint(
        'hot_desk_requests_email_fkey',
        'hot_desk_requests',
        type_='foreignkey')
    op.create_foreign_key(
        op.f('hot_desk_requests_requester_id_fkey'), 'hot_desk_requests',
        'users', ['requester_id'], ['token_id'])
    op.execute(
        'UPDATE hot_desk_requests hdrequest SET requester_id = ( SELECT '
        'token_id FROM users WHERE email=hdrequest.email )')
    op.drop_column('hot_desk_requests', 'email')
    op.execute(
        "ALTER TYPE hotdeskrequeststatusenum RENAME TO hotdeskrequeststatusenum_old;"
    )
    op.execute("ALTER TABLE hot_desk_requests ALTER status DROP DEFAULT")
    op.execute(
        "CREATE TYPE hotdeskrequeststatusenum AS ENUM('pending', 'approved', 'rejected', 'cancelled');"
    )
    op.execute(
        "ALTER TABLE hot_desk_requests ALTER COLUMN status TYPE hotdeskrequeststatusenum USING status::text::hotdeskrequeststatusenum;"
    )
    op.execute(
        "ALTER TABLE hot_desk_requests ALTER status SET DEFAULT 'pending'")
    op.execute("DROP TYPE hotdeskrequeststatusenum_old CASCADE;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'hot_desk_requests',
        sa.Column(
            'email', sa.VARCHAR(length=60), autoincrement=False,
            nullable=True))
    op.drop_constraint(
        op.f('hot_desk_requests_requester_id_fkey'),
        'hot_desk_requests',
        type_='foreignkey')
    op.create_foreign_key('hot_desk_requests_email_fkey', 'hot_desk_requests',
                          'users', ['email'], ['email'])
    op.add_column('hot_desk_requests',
                  sa.Column('complaint', sa.Text(), nullable=True))
    op.add_column('hot_desk_requests', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.execute(
        'UPDATE hot_desk_requests hdrequest SET email = '
        '( SELECT email FROM users WHERE token_id=hdrequest.requester_id )')
    op.drop_column('hot_desk_requests', 'search_vector')
    op.drop_column('hot_desk_requests', 'complaint')
    op.drop_column('hot_desk_requests', 'requester_id')
    op.drop_table('hot_desk_responses')
    op.execute(
        "UPDATE hot_desk_requests SET status = 'rejected' WHERE status = 'cancelled'"
    )
    op.execute(
        "ALTER TYPE hotdeskrequeststatusenum RENAME TO hotdeskrequeststatusenum_old;"
    )
    op.execute("ALTER TABLE hot_desk_requests ALTER status DROP DEFAULT")
    op.execute(
        "CREATE TYPE hotdeskrequeststatusenum AS ENUM('pending', 'approved', 'rejected');"
    )
    op.execute(
        "ALTER TABLE hot_desk_requests ALTER COLUMN status TYPE hotdeskrequeststatusenum USING status::text::hotdeskrequeststatusenum;"
    )
    op.execute(
        "ALTER TABLE hot_desk_requests ALTER status SET DEFAULT 'pending'")
    op.execute("DROP TYPE hotdeskrequeststatusenum_old CASCADE;")
    op.execute("DROP TYPE hotdeskresponsestatusenum CASCADE")
    #### end Alembic commands ####
