"""empty message

Revision ID: 7b7d87c75ac2
Revises: b66f378de753
Create Date: 2018-11-07 22:05:35.916702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7d87c75ac2'
down_revision = 'b66f378de753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_categories', sa.Column('low_in_stock', sa.Integer(), server_default='25', nullable=False))
    op.add_column('asset_categories', sa.Column('running_low', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_categories', 'running_low')
    op.drop_column('asset_categories', 'low_in_stock')
    # ### end Alembic commands ###
