"""empty message

Revision ID: 7f4942d6b052
Revises: cd351741392c
Create Date: 2018-08-08 18:00:51.355085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4942d6b052'
down_revision = 'cd351741392c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'serial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('serial', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
