"""empty message

Revision ID: 7fb1f286ef88
Revises: 72961503136b
Create Date: 2019-05-02 10:40:19.862198

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7fb1f286ef88'
down_revision = '72961503136b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_desk_requests',
                  sa.Column('complaint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_desk_requests', 'complaint')
    # ### end Alembic commands ###
