"""empty message

Revision ID: 84a254f3a1e4
Revises: 34befde26588
Create Date: 2019-07-16 10:56:56.494905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a254f3a1e4'
down_revision = '34befde26588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_warranties',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('deleted', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('updated_by', sa.String(), nullable=True),
                    sa.Column('deleted_by', sa.String(), nullable=True),
                    sa.Column('status', sa.Enum('active', 'expired',
                                                name='assetwarrantystatusenum'), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=True),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('asset_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f(
                        'asset_warranties_asset_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_asset_warranties'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_warranties')
    op.execute('DROP TYPE assetwarrantystatusenum')
    # ### end Alembic commands ###
