"""empty message

Revision ID: 8f6b3f05ade9
Revises: 5bcce4bb1b20
Create Date: 2019-05-21 11:50:33.237099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6b3f05ade9'
down_revision = '5bcce4bb1b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_desk_requests', sa.Column('complaint_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_desk_requests', 'complaint_created_at')
    # ### end Alembic commands ###
