"""empty message

Revision ID: 92f0c1bf2232
Revises: b536dd87ad92
Create Date: 2018-09-26 03:23:53.416525

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '92f0c1bf2232'
down_revision = 'b536dd87ad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'token_id',
            sa.String(length=60),
            server_default='-LNIg8hDPB6ymjBy2k3p',
            nullable=False))
    op.alter_column(
        'users',
        'role_id',
        existing_type=sa.VARCHAR(length=60),
        server_default='regular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_id')
    op.alter_column('users', 'role_id', existing_type=sa.VARCHAR())
    # ### end Alembic commands ###
