"""empty message

Revision ID: acd2816fd8a7
Revises: 441d41a4e7f7
Create Date: 2018-08-28 17:21:30.663086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd2816fd8a7'
down_revision = '441d41a4e7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('parent_id', sa.String(length=60), nullable=True),
    sa.Column('space_type_id', sa.String(length=60), nullable=False),
    sa.Column('center_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['space_type_id'], ['space_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spaces')
    # ### end Alembic commands ###
