"""empty message

Revision ID: b536dd87ad92
Revises: 56d5e806c83d
Create Date: 2018-09-25 15:02:35.771561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b536dd87ad92'
down_revision = '56d5e806c83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('space_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_space_id', 'asset', 'spaces', ['space_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_space_id', 'asset', type_='foreignkey')
    op.drop_column('asset', 'space_id')
    # ### end Alembic commands ###
