"""empty message

Revision ID: b66f378de753
Revises: d4a31fcfaf83
Create Date: 2018-11-02 12:50:33.767175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b66f378de753'
down_revision = 'd4a31fcfaf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    priority = postgresql.ENUM('key', 'not_key', name='priority')
    priority.create(op.get_bind())
    op.add_column('asset_categories', sa.Column('priority', priority, server_default='key', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_categories', 'priority')
    # ### end Alembic commands ###
