"""add search vector columns

Revision ID: c04f7a179a8d
Revises: 4c3a92e78dc9
Create Date: 2019-07-12 11:48:01.894149

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger

# revision identifiers, used by Alembic.
revision = 'c04f7a179a8d'
down_revision = '4c3a92e78dc9'
branch_labels = None
depends_on = None


def upgrade():
    # Fixes an issue with sqlalchemy searchable identified in issue #67
    sql = 'expressions.sql'
    with open(sql, 'r') as f:
        op.execute(f.read())
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'asset', 'search_vector', ['tag'])

    op.add_column('asset_categories', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'asset_categories', 'search_vector', ['name'])
    op.add_column('asset_repair_logs', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'asset_repair_logs',
                 'search_vector', ['issue_description'])
    op.add_column('centers', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'centers', 'search_vector', ['name'])
    op.add_column('comments', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'comments', 'search_vector', ['body'])
    op.add_column('hot_desk_requests', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'hot_desk_requests', 'search_vector',
                 ['hot_desk_ref_no', 'complaint'])
    op.add_column('users', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'users', 'search_vector', ['name', 'email'])
    op.add_column('work_orders', sa.Column(
        'search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'work_orders', 'search_vector',
                 ['title', 'description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'search_vector')
    op.drop_column('users', 'search_vector')
    op.drop_column('hot_desk_requests', 'search_vector')
    op.drop_column('comments', 'search_vector')
    op.drop_column('centers', 'search_vector')
    op.drop_column('asset_repair_logs', 'search_vector')
    op.drop_column('asset_categories', 'search_vector')
    op.drop_column('asset', 'search_vector')
    # ### end Alembic commands ###
