"""empty message

Revision ID: c7bbf7d35319
Revises: 7439f90b01ad
Create Date: 2019-03-07 10:50:30.772503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7bbf7d35319'
down_revision = '3ff6b067b60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE schedulestatusenum2 AS ENUM ('pending', 'done')")
    op.execute("UPDATE schedules SET status='pending' WHERE status='not_done'")
    op.execute(
        'ALTER TABLE schedules ALTER COLUMN status TYPE schedulestatusenum2 USING (status::text::schedulestatusenum2);'
    )
    op.execute("DROP TYPE schedulestatusenum CASCADE")
    op.execute("ALTER TYPE schedulestatusenum2 RENAME TO schedulestatusenum")
    op.add_column(
        'schedules',
        sa.Column('attachments', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'attachments')
    op.execute(
        "CREATE TYPE schedulestatusenum2 AS ENUM ('pending', 'done','not_done')"
    )
    op.execute(
        'ALTER TABLE schedules ALTER COLUMN status TYPE schedulestatusenum2 USING (status::text::schedulestatusenum2);'
    )
    op.execute("DROP TYPE schedulestatusenum CASCADE")
    op.execute("ALTER TYPE schedulestatusenum2 RENAME TO schedulestatusenum")
    # ### end Alembic commands ###
