"""empty message

Revision ID: c8c56c1f1a83
Revises: 170d80032bbe
Create Date: 2018-07-25 13:31:39.192590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8c56c1f1a83'
down_revision = '170d80032bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('image', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='centers_name_key')
    )
    op.add_column('asset', sa.Column('center_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_center_asset', 'asset', 'centers', ['center_id'], ['id'])
    op.add_column('users', sa.Column('center_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_center_user', 'users', 'centers', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_center_user', 'users', type_='foreignkey')
    op.drop_column('users', 'center_id')
    op.drop_constraint('fk_center_asset', 'asset', type_='foreignkey')
    op.drop_column('asset', 'center_id')
    op.drop_table('centers')
    # ### end Alembic commands ###
