"""empty message

Revision ID: cd351741392c
Revises: dedb89e83930
Create Date: 2018-08-08 12:00:09.394552

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cd351741392c'
down_revision = 'dedb89e83930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'asset_categories_name_key', 'asset_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asset_categories_name_key',
                                'asset_categories', ['name'])
    # ### end Alembic commands ###
