"""empty message

Revision ID: ce886b7c2b9f
Revises: 0d297689d275
Create Date: 2018-10-29 21:53:12.505986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce886b7c2b9f'
down_revision = '0d297689d275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    assignee_type = postgresql.ENUM(
        'user', 'space', name='assignee_type')
    assignee_type.create(op.get_bind())
    op.add_column(
        'asset', sa.Column('assigned_by', sa.String(length=60), nullable=True))
    op.add_column(
        'asset', sa.Column('assignee_id', sa.String(length=60), nullable=True))
    op.add_column(
        'asset',
        sa.Column(
            'assignee_type',
            assignee_type,
            server_default='space',
            nullable=False))
    op.add_column('asset',
                  sa.Column('date_assigned', sa.DateTime(), nullable=True))
    op.drop_constraint('fk_space_id', 'asset', type_='foreignkey')
    op.drop_column('asset', 'space_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'asset',
        sa.Column(
            'space_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_space_id', 'asset', 'spaces', ['space_id'],
                          ['id'])
    op.drop_column('asset', 'date_assigned')
    op.drop_column('asset', 'assignee_type')
    op.drop_column('asset', 'assignee_id')
    op.drop_column('asset', 'assigned_by')
    # ### end Alembic commands ###
