"""empty message

Revision ID: d4a31fcfaf83
Revises: ce886b7c2b9f
Create Date: 2018-10-31 00:52:01.169505

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4a31fcfaf83'
down_revision = 'ce886b7c2b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stock_counts', sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column('asset_category_id', sa.String(), nullable=False),
        sa.Column('center_id', sa.String(), nullable=False),
        sa.Column('token_id', sa.String(), nullable=False),
        sa.Column('week', sa.Integer(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['asset_category_id'],
            ['asset_categories.id'],
        ), sa.ForeignKeyConstraint(
            ['center_id'],
            ['centers.id'],
        ), sa.ForeignKeyConstraint(
            ['token_id'],
            ['users.token_id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_counts')
    # ### end Alembic commands ###
