"""empty message

Revision ID: ee639dd38b3f
Revises: 259f1e1812fb
Create Date: 2019-04-15 20:08:58.388088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee639dd38b3f'
down_revision = '259f1e1812fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'custom_occurence',
                    new_column_name='custom_occurrence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'custom_occurrence',
                    new_column_name='custom_occurence')
    # ### end Alembic commands ###
