"""empty message

Revision ID: fb1cd924081f
Revises: 1cb6cb3b4bda
Create Date: 2019-07-11 12:37:08.452970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1cd924081f'
down_revision = '1cb6cb3b4bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_supporting_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(length=60), nullable=False),
    sa.Column('document_type', sa.Enum('purchase_receipts', 'repair_receipts', name='assetsupportingdocumenttypeenum'), nullable=False),
    sa.Column('asset_id', sa.String(length=60), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('asset_supporting_documents_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_supporting_documents'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_supporting_documents')
    op.execute('DROP TYPE assetsupportingdocumenttypeenum')
    # ### end Alembic commands ###
