"""empty message

Revision ID: fbd06aa0496e
Revises: 516787d37e0b
Create Date: 2019-02-20 15:29:34.699680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbd06aa0496e'
down_revision = '516787d37e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "create type frequencyenum as enum ('no_repeat', 'daily', 'weekly', 'weekday', 'custom')"
    )
    op.execute("create type statusenum as enum ('enabled', 'disabled')")
    op.add_column(
        'work_orders',
        sa.Column(
            'custom_occurence',
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True))
    op.add_column(
        'work_orders',
        sa.Column(
            'frequency',
            sa.Enum(
                'no_repeat',
                'daily',
                'weekly',
                'weekday',
                'custom',
                name='frequencyenum'),
            server_default='daily',
            nullable=False))
    op.add_column(
        'work_orders',
        sa.Column(
            'status',
            sa.Enum('enabled', 'disabled', name='statusenum'),
            server_default='enabled',
            nullable=False))
    op.drop_constraint(
        'work_orders_center_id_fkey', 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'center_id')
    op.drop_column('work_orders', 'frequency_type')
    op.drop_column('work_orders', 'frequency_units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop type frequencyenum CASCADE")
    op.execute("drop type statusenum CASCADE")
    op.add_column(
        'work_orders',
        sa.Column(
            'frequency_units',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True))
    op.add_column(
        'work_orders',
        sa.Column(
            'frequency_type',
            postgresql.ENUM(
                'hours', 'days', 'weeks', 'months', name='frequencytypesenum'),
            autoincrement=False,
            nullable=True))
    op.add_column(
        'work_orders',
        sa.Column(
            'center_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_orders_center_id_fkey', 'work_orders',
                          'centers', ['center_id'], ['id'])
    op.drop_column('work_orders', 'custom_occurence')
    # ### end Alembic commands ###
